export const USER_ROLES = {
  STUDENT: 'STUDENT',
  LECTURER: 'LECTURER',
  INTERNAL_MODERATOR: 'INTERNAL_MODERATOR',
  PROGRAMME_COORDINATOR: 'PROGRAMME_COORDINATOR',
  ADMIN: 'ADMIN',
} as const

export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES]
